[package]
name = "bsc-parse"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22.1"

[dependencies]
bsc-lexer = { path = "../bsc-lexer" }
lalrpop-util = { version = "0.22.1", features = ["lexer", "unicode"] }
